<?php

namespace CompBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * industryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class industryRepository extends EntityRepository
{

}
